### ISSUE TITLE
Add Coveralls

### ISSUE THREAD

**Issue by techman83** [plugorgau/eventstreamr-station#65]
Coveralls + Perl are a thing! -> https://coveralls.io/r/plugorgau/eventstreamr-station

```yaml
install:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest Dist::Zilla::App::Command::cover

after_success:
  - dzil cover -outputdir cover_db -report coveralls
```

```md
 [![Coverage Status](https://coveralls.io/repos/plugorgau/eventstreamr-station/badge.svg?branch=master)](https://coveralls.io/r/plugorgau/eventstreamr-station?branch=master)
```
